INSERT INTO Patient(id, name, email, phone) values (101, 'Example', 'example@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (102, 'Felix', 'felix@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (103, 'Liron', 'liron@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (104, 'Alex', 'alex@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (105, 'Max', 'max@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (106, 'Sam', 'Sam@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (107, 'Harsh', 'Harsh@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (108, 'Sarah', 'Sarah@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (109, 'Alan', 'Alan@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (110, 'Ayesha', 'Ayesha@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (111, 'Ashish', 'Ashish@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (112, 'Ben', 'Ben@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (113, 'Niel', 'Niel@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (114, 'Priya', 'Priya@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (115, 'Abhi', 'Abhi@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (116, 'John', 'John@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (117, 'Kanye', 'Kanye@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (118, 'A$AP Rocky', 'A$AP@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (119, 'Frank Ocean', 'blonde@gmail.com', '7046269313')
INSERT INTO Patient(id, name, email, phone) values (120, '2 Chainz', 'twochainz@gmail.com', '7046269313')
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (301, "Situation", "Background", "Assessment", "Recomendation", "11/04/2018", "Dr. Dre",101)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (302, "Situation", "Background", "Assessment", "Recomendation", "11/04/2017", "Takeoff",101)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (303, "Situation", "Background", "Assessment", "Recomendation", "11/04/2016", "Drake",101)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (304, "Situation", "Background", "Assessment", "Recomendation", "11/04/2015", "Kendrick Lamar",102)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (305, "Situation", "Background", "Assessment", "Recomendation", "11/04/2014", "Saheli",102)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (306, "Situation", "Background", "Assessment", "Recomendation", "11/04/2013", "J.Cole",103)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (307, "Situation", "Background", "Assessment", "Recomendation", "11/04/2012", "Cardi B",104)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (308, "Situation", "Background", "Assessment", "Recomendation", "11/04/2011", "Lil Yachty",105)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (309, "Situation", "Background", "Assessment", "Recomendation", "11/04/2010", "Post Malone",105)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (310, "Situation", "Background", "Assessment", "Recomendation", "11/04/2009", "The Game",105)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (311, "Situation", "Background", "Assessment", "Recomendation", "11/04/2008", "Kid Cudi",105)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (312, "Situation", "Background", "Assessment", "Recomendation", "11/04/2007", "Pusha T",106)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (313, "Situation", "Background", "Assessment", "Recomendation", "11/04/2006", "Jaden Smith",107)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (314, "Situation", "Background", "Assessment", "Recomendation", "11/04/2005", "Kendrick Lamar",108)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (315, "Situation", "Background", "Assessment", "Recomendation", "11/04/2004", "Saheli",109)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (316, "Situation", "Background", "Assessment", "Recomendation", "11/04/2003", "J.Cole",110)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (317, "Situation", "Background", "Assessment", "Recomendation", "11/04/2002", "Cardi B",111)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (318, "Situation", "Background", "Assessment", "Recomendation", "11/04/2001", "Lil Yachty",112)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (320, "Situation", "Background", "Assessment", "Recomendation", "11/04/2000", "Post Malone",112)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (321, "Situation", "Background", "Assessment", "Recomendation", "11/04/1999", "The Game",112)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (322, "Situation", "Background", "Assessment", "Recomendation", "11/04/1998", "Kid Cudi",113)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (323, "Situation", "Background", "Assessment", "Recomendation", "11/04/1997", "Kendrick Lamar",114)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (324, "Situation", "Background", "Assessment", "Recomendation", "11/04/1996", "Saheli",115)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (325, "Situation", "Background", "Assessment", "Recomendation", "11/04/1995", "J.Cole",116)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (326, "Situation", "Background", "Assessment", "Recomendation", "11/04/1994", "Cardi B",117)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (327, "Situation", "Background", "Assessment", "Recomendation", "11/04/1993", "Lil Yachty",118)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (328, "Situation", "Background", "Assessment", "Recomendation", "11/04/1992", "Post Malone",119)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (329, "Situation", "Background", "Assessment", "Recomendation", "11/04/1991", "The Game",120)
INSERT INTO SBAR(id,situation,background,assessment,recommendation, date, provider,sbar_id) values (330, "Situation", "Background", "Assessment", "Recomendation", "11/04/1990", "Kid Cudi",120)